version: '3.8'

services:
  db:
    image: postgres:alpine
    container_name: db
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: db_samehere
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ../sql/database-init.sql:/docker-entrypoint-initdb.d/create_tables.sql
    ports:
      - '5001:5432'

  api:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    container_name: api_samehere
    depends_on:
      - db
    ports:
      - '5000:5000'
    volumes:
      - ../:/app
      - /app/node_modules

volumes:
  pgdata:
